In [5]:
# Dependencies
import numpy as np
import datetime as dt
import pandas as pd

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [6]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [7]:
# Create our session (link) from Python to the DB
session = Session(engine)

## D1: Determine the Summary Statistics for June

In [8]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 
july = dt.date(2017,7,1)
june = dt.date(2017,6,1)

In [9]:
#  3. Convert the June temperatures to a list.
results = []
results = session.query(Measurement.date, Measurement.prcp).filter(Measurement.date>=june,Measurement.date<july).all()
print(results)

[('2017-06-01', 0.0), ('2017-06-02', 0.0), ('2017-06-03', 0.02), ('2017-06-04', 0.0), ('2017-06-05', 0.0), ('2017-06-06', 0.0), ('2017-06-07', 0.0), ('2017-06-08', 0.0), ('2017-06-09', 0.0), ('2017-06-10', 0.04), ('2017-06-11', 0.08), ('2017-06-12', 0.02), ('2017-06-13', 0.0), ('2017-06-14', 0.0), ('2017-06-15', 0.0), ('2017-06-16', 0.0), ('2017-06-17', 0.0), ('2017-06-18', 0.05), ('2017-06-19', 0.0), ('2017-06-20', 0.02), ('2017-06-21', 0.0), ('2017-06-22', 0.0), ('2017-06-23', 0.0), ('2017-06-24', 0.06), ('2017-06-25', 0.0), ('2017-06-26', 0.0), ('2017-06-27', 0.0), ('2017-06-28', 0.0), ('2017-06-29', 0.0), ('2017-06-30', 0.08), ('2017-06-01', 0.03), ('2017-06-02', 0.1), ('2017-06-03', 0.2), ('2017-06-04', 0.15), ('2017-06-05', 0.0), ('2017-06-06', 0.0), ('2017-06-07', 0.0), ('2017-06-08', 0.02), ('2017-06-09', 0.02), ('2017-06-10', 0.21), ('2017-06-11', 0.24), ('2017-06-12', 0.19), ('2017-06-13', 0.36), ('2017-06-14', 0.27), ('2017-06-15', 0.17), ('2017-06-16', 0.02), ('2017-06-17', 0.35), ('2017-06-18', 0.25), ('2017-06-19', 0.05), ('2017-06-20', 0.05), ('2017-06-21', 0.02), ('2017-06-22', 0.1), ('2017-06-23', 0.0), ('2017-06-24', 0.0), ('2017-06-25', 0.08), ('2017-06-26', 0.02), ('2017-06-27', 0.0), ('2017-06-28', 0.01), ('2017-06-29', 0.03), ('2017-06-30', 0.04), ('2017-06-01', 0.0), ('2017-06-02', 0.15), ('2017-06-03', 0.16), ('2017-06-04', 0.05), ('2017-06-05', 0.02), ('2017-06-06', 0.0), ('2017-06-07', 0.0), ('2017-06-08', 0.01), ('2017-06-09', 0.0), ('2017-06-10', 0.53), ('2017-06-11', 0.14), ('2017-06-12', 0.35), ('2017-06-13', 0.1), ('2017-06-14', 0.21), ('2017-06-15', 0.3), ('2017-06-16', 0.02), ('2017-06-17', 0.02), ('2017-06-18', 0.18), ('2017-06-19', 0.19), ('2017-06-20', 0.17), ('2017-06-23', None), ('2017-06-26', None), ('2017-06-29', None), ('2017-06-30', 0.0), ('2017-06-02', None), ('2017-06-05', None), ('2017-06-06', None), ('2017-06-07', None), ('2017-06-08', None), ('2017-06-09', None), ('2017-06-13', None), ('2017-06-14', None), ('2017-06-15', None), ('2017-06-16', None), ('2017-06-19', None), ('2017-06-20', None), ('2017-06-21', None), ('2017-06-22', 0.0), ('2017-06-23', 0.0), ('2017-06-26', None), ('2017-06-27', 0.0), ('2017-06-28', 0.0), ('2017-06-29', 0.0), ('2017-06-30', 0.12), ('2017-06-01', 0.0), ('2017-06-02', 0.0), ('2017-06-03', 0.15), ('2017-06-04', 0.0), ('2017-06-05', 0.0), ('2017-06-06', 0.0), ('2017-06-07', 0.0), ('2017-06-08', 0.0), ('2017-06-09', 0.0), ('2017-06-10', 0.13), ('2017-06-11', 0.25), ('2017-06-12', 0.14), ('2017-06-13', 0.03), ('2017-06-14', 0.06), ('2017-06-15', 0.0), ('2017-06-16', 0.0), ('2017-06-17', 0.0), ('2017-06-18', 0.0), ('2017-06-19', 0.01), ('2017-06-21', None), ('2017-06-22', 0.0), ('2017-06-23', 0.05), ('2017-06-24', 0.0), ('2017-06-25', 0.0), ('2017-06-26', 0.0), ('2017-06-27', 0.0), ('2017-06-28', 0.0), ('2017-06-29', 0.0), ('2017-06-30', 0.07), ('2017-06-01', 0.0), ('2017-06-02', 0.09), ('2017-06-03', 0.08), ('2017-06-04', 0.13), ('2017-06-05', 0.05), ('2017-06-06', 0.0), ('2017-06-07', 0.0), ('2017-06-08', 0.0), ('2017-06-09', 0.02), ('2017-06-10', 0.62), ('2017-06-11', 0.74), ('2017-06-12', 0.24), ('2017-06-13', 0.24), ('2017-06-14', 0.22), ('2017-06-15', 0.55), ('2017-06-16', 0.06), ('2017-06-17', 0.07), ('2017-06-18', 0.24), ('2017-06-19', 0.08), ('2017-06-20', 0.0), ('2017-06-21', 0.19), ('2017-06-22', 0.06), ('2017-06-23', 0.12), ('2017-06-24', 0.36), ('2017-06-25', 0.02), ('2017-06-26', 0.06), ('2017-06-27', 0.01), ('2017-06-28', 0.0), ('2017-06-29', 0.0), ('2017-06-30', 0.01), ('2017-06-01', 0.01), ('2017-06-03', None), ('2017-06-04', 0.82), ('2017-06-05', 0.01), ('2017-06-06', 0.0), ('2017-06-07', 0.01), ('2017-06-08', 0.0), ('2017-06-10', None), ('2017-06-11', 0.7), ('2017-06-12', 0.81), ('2017-06-13', 0.65), ('2017-06-14', 0.81), ('2017-06-15', 1.69), ('2017-06-16', 0.1), ('2017-06-17', 0.1), ('2017-06-18', 0.7), ('2017-06-19', 0.4), ('2017-06-20', 0.31), ('2017-06-21', 0.3), ('2017-06-22', 0.28), ('2017-06-23', 0.5), ('2017-06-24', 0.22), ('2017-06-25', 0.5), ('2017-06-26', 0.02), ('2017-06-27', 0.1), ('2017-06-28', 0.02), ('2017-06-29', 0.04), ('2017-06-30', 0.2)]

In [10]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
df = pd.DataFrame(results, columns = ['date','precipitation'])
df.set_index(df['date'], inplace=True)
df = df.sort_index()
print(df.to_string(index=False))

       date  precipitation
 2017-06-01           0.00
 2017-06-01           0.00
 2017-06-01           0.00
 2017-06-01           0.01
 2017-06-01           0.03
 2017-06-01           0.00
 2017-06-02           0.09
 2017-06-02           0.15
 2017-06-02            NaN
 2017-06-02           0.10
 2017-06-02           0.00
 2017-06-02           0.00
 2017-06-03           0.02
 2017-06-03           0.20
 2017-06-03            NaN
 2017-06-03           0.16
 2017-06-03           0.08
 2017-06-03           0.15
 2017-06-04           0.00
 2017-06-04           0.00
 2017-06-04           0.82
 2017-06-04           0.15
 2017-06-04           0.05
 2017-06-04           0.13
 2017-06-05            NaN
 2017-06-05           0.00
 2017-06-05           0.01
 2017-06-05           0.05
 2017-06-05           0.00
 2017-06-05           0.02
 2017-06-05           0.00
 2017-06-06           0.00
 2017-06-06           0.00
 2017-06-06           0.00
 2017-06-06            NaN
 2017-06-06           0.00
 2017-06-06           0.00
 2017-06-06           0.00
 2017-06-07           0.00
 2017-06-07           0.00
 2017-06-07           0.00
 2017-06-07            NaN
 2017-06-07           0.00
 2017-06-07           0.00
 2017-06-07           0.01
 2017-06-08           0.00
 2017-06-08           0.00
 2017-06-08           0.00
 2017-06-08            NaN
 2017-06-08           0.01
 2017-06-08           0.02
 2017-06-08           0.00
 2017-06-09            NaN
 2017-06-09           0.02
 2017-06-09           0.00
 2017-06-09           0.00
 2017-06-09           0.00
 2017-06-09           0.02
 2017-06-10           0.04
 2017-06-10            NaN
 2017-06-10           0.62
 2017-06-10           0.53
 2017-06-10           0.13
 2017-06-10           0.21
 2017-06-11           0.14
 2017-06-11           0.24
 2017-06-11           0.74
 2017-06-11           0.70
 2017-06-11           0.08
 2017-06-11           0.25
 2017-06-12           0.02
 2017-06-12           0.19
 2017-06-12           0.24
 2017-06-12           0.35
 2017-06-12           0.81
 2017-06-12           0.14
 2017-06-13           0.10
 2017-06-13            NaN
 2017-06-13           0.65
 2017-06-13           0.36
 2017-06-13           0.24
 2017-06-13           0.03
 2017-06-13           0.00
 2017-06-14           0.21
 2017-06-14           0.00
 2017-06-14           0.06
 2017-06-14           0.27
 2017-06-14           0.81
 2017-06-14            NaN
 2017-06-14           0.22
 2017-06-15           0.00
 2017-06-15           0.00
 2017-06-15           0.17
 2017-06-15           0.55
 2017-06-15            NaN
 2017-06-15           1.69
 2017-06-15           0.30
 2017-06-16           0.06
 2017-06-16           0.02
 2017-06-16            NaN
 2017-06-16           0.00
 2017-06-16           0.00
 2017-06-16           0.02
 2017-06-16           0.10
 2017-06-17           0.00
 2017-06-17           0.07
 2017-06-17           0.10
 2017-06-17           0.35
 2017-06-17           0.00
 2017-06-17           0.02
 2017-06-18           0.70
 2017-06-18           0.25
 2017-06-18           0.00
 2017-06-18           0.05
 2017-06-18           0.18
 2017-06-18           0.24
 2017-06-19           0.01
 2017-06-19            NaN
 2017-06-19           0.40
 2017-06-19           0.19
 2017-06-19           0.00
 2017-06-19           0.08
 2017-06-19           0.05
 2017-06-20           0.00
 2017-06-20           0.31
 2017-06-20            NaN
 2017-06-20           0.17
 2017-06-20           0.05
 2017-06-20           0.02
 2017-06-21           0.19
 2017-06-21            NaN
 2017-06-21           0.02
 2017-06-21           0.00
 2017-06-21            NaN
 2017-06-21           0.30
 2017-06-22           0.00
 2017-06-22           0.00
 2017-06-22           0.10
 2017-06-22           0.28
 2017-06-22           0.06
 2017-06-22           0.00
 2017-06-23           0.00
 2017-06-23           0.00
 2017-06-23           0.50
 2017-06-23           0.12
 2017-06-23           0.00
 2017-06-23            NaN
 2017-06-23           0.05
 2017-06-24           0.00
 2017-06-24           0.36
 2017-06-24           0.00
 2017-06-24           0.06
 2017-06-24           0.22
 2017-06-25           0.00
 2017-06-25           0.08
 2017-06-25           0.50
 2017-06-25           0.02
 2017-06-25           0.00
 2017-06-26           0.02
 2017-06-26           0.00
 2017-06-26           0.02
 2017-06-26           0.06
 2017-06-26            NaN
 2017-06-26           0.00
 2017-06-26            NaN
 2017-06-27           0.01
 2017-06-27           0.00
 2017-06-27           0.00
 2017-06-27           0.10
 2017-06-27           0.00
 2017-06-27           0.00
 2017-06-28           0.00
 2017-06-28           0.00
 2017-06-28           0.01
 2017-06-28           0.02
 2017-06-28           0.00
 2017-06-28           0.00
 2017-06-29           0.00
 2017-06-29           0.04
 2017-06-29            NaN
 2017-06-29           0.00
 2017-06-29           0.03
 2017-06-29           0.00
 2017-06-29           0.00
 2017-06-30           0.01
 2017-06-30           0.12
 2017-06-30           0.00
 2017-06-30           0.08
 2017-06-30           0.04
 2017-06-30           0.07
 2017-06-30           0.20

In [11]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.
df.describe()

       precipitation
count     171.000000
mean        0.120000
std         0.217726
min         0.000000
25%         0.000000
50%         0.020000
75%         0.150000
max         1.690000

## D2: Determine the Summary Statistics for December

In [12]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.
january = dt.date(2017,1,1)
december = dt.date(2016,12,1)

In [13]:
# 7. Convert the December temperatures to a list.
results = []
results = session.query(Measurement.date, Measurement.prcp).filter(Measurement.date>=december,Measurement.date<january).all()
print(results)

[('2016-12-01', 0.12), ('2016-12-02', 0.03), ('2016-12-03', 0.0), ('2016-12-04', 0.03), ('2016-12-05', 0.43), ('2016-12-06', 0.02), ('2016-12-07', 0.0), ('2016-12-08', 0.03), ('2016-12-09', 0.52), ('2016-12-10', 0.05), ('2016-12-11', 0.04), ('2016-12-12', 0.01), ('2016-12-13', 0.05), ('2016-12-14', 0.03), ('2016-12-15', 0.0), ('2016-12-16', 0.0), ('2016-12-17', 0.01), ('2016-12-18', 0.13), ('2016-12-19', 0.01), ('2016-12-20', 0.0), ('2016-12-21', 0.0), ('2016-12-22', 0.01), ('2016-12-23', 0.01), ('2016-12-24', 0.01), ('2016-12-25', 0.0), ('2016-12-26', 0.02), ('2016-12-27', 0.0), ('2016-12-28', 0.02), ('2016-12-29', 0.04), ('2016-12-30', 0.12), ('2016-12-31', 0.01), ('2016-12-01', 0.33), ('2016-12-02', 0.3), ('2016-12-03', 0.04), ('2016-12-04', 0.1), ('2016-12-05', 0.34), ('2016-12-06', 0.02), ('2016-12-07', 0.17), ('2016-12-08', 0.03), ('2016-12-09', 0.34), ('2016-12-10', 0.02), ('2016-12-11', 0.02), ('2016-12-12', 0.01), ('2016-12-13', 0.1), ('2016-12-14', 0.05), ('2016-12-15', 0.02), ('2016-12-16', 0.01), ('2016-12-17', 0.11), ('2016-12-18', 0.29), ('2016-12-19', 0.21), ('2016-12-20', 0.02), ('2016-12-21', 0.03), ('2016-12-22', 0.17), ('2016-12-23', 0.1), ('2016-12-24', 0.14), ('2016-12-25', 0.03), ('2016-12-26', 0.26), ('2016-12-27', 0.03), ('2016-12-28', 0.09), ('2016-12-29', 0.18), ('2016-12-30', 0.21), ('2016-12-31', 0.62), ('2016-12-01', 0.07), ('2016-12-02', 0.4), ('2016-12-03', 0.26), ('2016-12-04', 0.0), ('2016-12-05', 0.2), ('2016-12-07', None), ('2016-12-08', 0.02), ('2016-12-09', 0.26), ('2016-12-10', 0.0), ('2016-12-12', None), ('2016-12-13', 0.34), ('2016-12-14', 0.12), ('2016-12-15', 0.07), ('2016-12-16', 0.0), ('2016-12-17', 0.0), ('2016-12-18', 0.04), ('2016-12-19', 0.0), ('2016-12-20', 0.0), ('2016-12-21', 0.09), ('2016-12-22', 0.05), ('2016-12-23', 0.03), ('2016-12-24', 0.13), ('2016-12-26', None), ('2016-12-27', 0.02), ('2016-12-28', 0.01), ('2016-12-29', 0.56), ('2016-12-30', 0.29), ('2016-12-31', 0.36), ('2016-12-01', None), ('2016-12-02', None), ('2016-12-05', None), ('2016-12-06', None), ('2016-12-07', None), ('2016-12-08', 0.27), ('2016-12-09', None), ('2016-12-12', 0.02), ('2016-12-13', None), ('2016-12-14', None), ('2016-12-15', None), ('2016-12-16', None), ('2016-12-19', None), ('2016-12-20', None), ('2016-12-21', 0.06), ('2016-12-22', None), ('2016-12-23', None), ('2016-12-28', None), ('2016-12-29', None), ('2016-12-30', None), ('2016-12-01', 0.16), ('2016-12-02', 0.01), ('2016-12-03', 0.02), ('2016-12-04', 0.32), ('2016-12-05', 0.45), ('2016-12-06', 0.0), ('2016-12-07', 0.07), ('2016-12-08', 0.01), ('2016-12-10', None), ('2016-12-11', 0.06), ('2016-12-12', 0.0), ('2016-12-13', 0.15), ('2016-12-14', 0.05), ('2016-12-15', 0.0), ('2016-12-16', 0.0), ('2016-12-17', 0.16), ('2016-12-18', 0.27), ('2016-12-19', 0.02), ('2016-12-20', 0.01), ('2016-12-21', 0.06), ('2016-12-22', 0.14), ('2016-12-23', 0.02), ('2016-12-24', 0.06), ('2016-12-25', 0.0), ('2016-12-26', 0.06), ('2016-12-27', 0.0), ('2016-12-28', 0.06), ('2016-12-29', 0.05), ('2016-12-30', 0.07), ('2016-12-01', 0.37), ('2016-12-02', 0.35), ('2016-12-03', 0.77), ('2016-12-04', 0.04), ('2016-12-05', 0.22), ('2016-12-06', 0.0), ('2016-12-07', 0.12), ('2016-12-08', 0.07), ('2016-12-09', 0.31), ('2016-12-10', 0.02), ('2016-12-11', 0.0), ('2016-12-12', 0.0), ('2016-12-13', 0.04), ('2016-12-14', 0.92), ('2016-12-15', 0.14), ('2016-12-16', 0.03), ('2016-12-17', 0.07), ('2016-12-18', 0.16), ('2016-12-19', 0.03), ('2016-12-20', 0.0), ('2016-12-21', 0.11), ('2016-12-22', 0.86), ('2016-12-23', 0.24), ('2016-12-24', 0.2), ('2016-12-25', 0.02), ('2016-12-26', 0.22), ('2016-12-27', 0.05), ('2016-12-28', 0.09), ('2016-12-29', 0.52), ('2016-12-30', 0.29), ('2016-12-31', 0.25), ('2016-12-01', 0.72), ('2016-12-02', 1.27), ('2016-12-03', 1.62), ('2016-12-04', 0.31), ('2016-12-05', 1.6), ('2016-12-06', 0.0), ('2016-12-07', 0.02), ('2016-12-08', 0.03), ('2016-12-09', 0.42), ('2016-12-10', 0.04), ('2016-12-11', 0.13), ('2016-12-12', 0.01), ('2016-12-13', 0.09), ('2016-12-14', 0.33), ('2016-12-15', 0.03), ('2016-12-16', 0.0), ('2016-12-18', None), ('2016-12-19', 0.15), ('2016-12-20', 0.0), ('2016-12-21', 0.55), ('2016-12-22', 1.24), ('2016-12-23', 0.83), ('2016-12-24', 1.08), ('2016-12-25', 0.38), ('2016-12-26', 1.48), ('2016-12-27', 0.14), ('2016-12-28', 0.14), ('2016-12-29', 1.03), ('2016-12-30', 2.37), ('2016-12-31', 0.9)]

In [14]:
# 8. Create a DataFrame from the list of temperatures for the month of December. 
df = pd.DataFrame(results, columns = ['date','precipitation'])
df.set_index(df['date'], inplace=True)
df = df.sort_index()
print(df.to_string(index=False))

       date  precipitation
 2016-12-01           0.12
 2016-12-01           0.16
 2016-12-01           0.07
 2016-12-01           0.37
 2016-12-01           0.33
 2016-12-01           0.72
 2016-12-01            NaN
 2016-12-02           1.27
 2016-12-02            NaN
 2016-12-02           0.35
 2016-12-02           0.03
 2016-12-02           0.01
 2016-12-02           0.40
 2016-12-02           0.30
 2016-12-03           0.26
 2016-12-03           0.77
 2016-12-03           0.02
 2016-12-03           1.62
 2016-12-03           0.00
 2016-12-03           0.04
 2016-12-04           0.31
 2016-12-04           0.00
 2016-12-04           0.10
 2016-12-04           0.03
 2016-12-04           0.32
 2016-12-04           0.04
 2016-12-05           0.43
 2016-12-05           0.34
 2016-12-05           0.22
 2016-12-05           1.60
 2016-12-05           0.20
 2016-12-05            NaN
 2016-12-05           0.45
 2016-12-06           0.02
 2016-12-06           0.00
 2016-12-06           0.02
 2016-12-06            NaN
 2016-12-06           0.00
 2016-12-06           0.00
 2016-12-07           0.12
 2016-12-07           0.00
 2016-12-07            NaN
 2016-12-07           0.07
 2016-12-07           0.17
 2016-12-07            NaN
 2016-12-07           0.02
 2016-12-08           0.01
 2016-12-08           0.02
 2016-12-08           0.27
 2016-12-08           0.03
 2016-12-08           0.07
 2016-12-08           0.03
 2016-12-08           0.03
 2016-12-09           0.52
 2016-12-09            NaN
 2016-12-09           0.26
 2016-12-09           0.31
 2016-12-09           0.42
 2016-12-09           0.34
 2016-12-10           0.02
 2016-12-10           0.05
 2016-12-10           0.00
 2016-12-10           0.04
 2016-12-10           0.02
 2016-12-10            NaN
 2016-12-11           0.02
 2016-12-11           0.06
 2016-12-11           0.04
 2016-12-11           0.00
 2016-12-11           0.13
 2016-12-12           0.00
 2016-12-12           0.01
 2016-12-12           0.01
 2016-12-12           0.02
 2016-12-12           0.01
 2016-12-12            NaN
 2016-12-12           0.00
 2016-12-13           0.09
 2016-12-13           0.05
 2016-12-13            NaN
 2016-12-13           0.15
 2016-12-13           0.04
 2016-12-13           0.34
 2016-12-13           0.10
 2016-12-14           0.33
 2016-12-14           0.05
 2016-12-14           0.92
 2016-12-14            NaN
 2016-12-14           0.12
 2016-12-14           0.03
 2016-12-14           0.05
 2016-12-15           0.14
 2016-12-15           0.07
 2016-12-15           0.02
 2016-12-15            NaN
 2016-12-15           0.00
 2016-12-15           0.00
 2016-12-15           0.03
 2016-12-16           0.00
 2016-12-16           0.01
 2016-12-16            NaN
 2016-12-16           0.03
 2016-12-16           0.00
 2016-12-16           0.00
 2016-12-16           0.00
 2016-12-17           0.00
 2016-12-17           0.11
 2016-12-17           0.07
 2016-12-17           0.16
 2016-12-17           0.01
 2016-12-18           0.13
 2016-12-18           0.29
 2016-12-18            NaN
 2016-12-18           0.04
 2016-12-18           0.16
 2016-12-18           0.27
 2016-12-19           0.01
 2016-12-19           0.03
 2016-12-19           0.02
 2016-12-19           0.21
 2016-12-19           0.15
 2016-12-19            NaN
 2016-12-19           0.00
 2016-12-20            NaN
 2016-12-20           0.00
 2016-12-20           0.02
 2016-12-20           0.00
 2016-12-20           0.01
 2016-12-20           0.00
 2016-12-20           0.00
 2016-12-21           0.06
 2016-12-21           0.11
 2016-12-21           0.00
 2016-12-21           0.03
 2016-12-21           0.09
 2016-12-21           0.55
 2016-12-21           0.06
 2016-12-22           0.05
 2016-12-22           0.17
 2016-12-22            NaN
 2016-12-22           0.01
 2016-12-22           0.86
 2016-12-22           0.14
 2016-12-22           1.24
 2016-12-23           0.24
 2016-12-23           0.83
 2016-12-23           0.03
 2016-12-23           0.01
 2016-12-23           0.02
 2016-12-23            NaN
 2016-12-23           0.10
 2016-12-24           1.08
 2016-12-24           0.01
 2016-12-24           0.20
 2016-12-24           0.13
 2016-12-24           0.06
 2016-12-24           0.14
 2016-12-25           0.02
 2016-12-25           0.00
 2016-12-25           0.03
 2016-12-25           0.38
 2016-12-25           0.00
 2016-12-26           0.26
 2016-12-26            NaN
 2016-12-26           0.22
 2016-12-26           1.48
 2016-12-26           0.02
 2016-12-26           0.06
 2016-12-27           0.02
 2016-12-27           0.05
 2016-12-27           0.03
 2016-12-27           0.00
 2016-12-27           0.14
 2016-12-27           0.00
 2016-12-28           0.01
 2016-12-28           0.09
 2016-12-28           0.06
 2016-12-28           0.09
 2016-12-28            NaN
 2016-12-28           0.02
 2016-12-28           0.14
 2016-12-29           0.56
 2016-12-29            NaN
 2016-12-29           0.18
 2016-12-29           0.52
 2016-12-29           0.04
 2016-12-29           1.03
 2016-12-29           0.05
 2016-12-30           0.29
 2016-12-30           0.29
 2016-12-30           0.12
 2016-12-30           0.07
 2016-12-30           0.21
 2016-12-30            NaN
 2016-12-30           2.37
 2016-12-31           0.01
 2016-12-31           0.62
 2016-12-31           0.36
 2016-12-31           0.25
 2016-12-31           0.90

In [15]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
df.describe()

       precipitation
count     178.000000
mean        0.199494
std         0.342967
min         0.000000
25%         0.020000
50%         0.060000
75%         0.247500
max         2.370000